spring:
  application:
    name: uaa
server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
security:
  user: 
    password: none
  basic: 
    enabled: false
  oauth2:
    client:
      clientId: myclient
      clientSecret: password 
      scope: all
    authorization: 
      checkTokenAccess: isAuthenticated()       
management:
  security:
    enabled: false  