version: '2'
services:
  eureka:
    image: eureka
    ports:
     - "8761:8761"
  apigateway:
    image: apigateway
    depends_on:
     - eureka
    ports:
     - "8080:8080"
  uaa:
    image: uaa
    depends_on:
     - eureka
  flightsearch:
    image: flightsearch
    depends_on:
     - eureka
  
  