spring:
  application:
    name: flightsearch
server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
security:
  basic:
    enabled: false