spring:
  application:
    name: flightsearch
server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
security:
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    client:
      clientId: myclient
      clientSecret: password  
    resource:
      tokenInfoUri: http://localhost:8080/uaa/oauth/check_token
management:
  security:
    enabled: false      