spring:
  application:
    name: apigateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
zuul:
  routes:
    uaa:
      path: /uaa/**
      serviceId: uaa
    flightsearch:
      path: /flightsearch/**
      serviceId: flightsearch
security:
  basic:
    enabled: false