spring:
  application:
    name: apigateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
zuul:
  routes:
    uaa:
      path: /uaa/**
      serviceId: uaa
      sensitiveHeaders:  
    flightsearch: 
      path: /flightsearch/**
      serviceId: flightsearch
security:
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    client:
      clientId: myclient
      clientSecret: password  
management:
  security:
    enabled: false      