spring: 
  application:
    name: apigateway
      
# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
    preferIpAddress: true

zuul:
  routes:
    flightsearch: 
      path: /flightsearch/**
      url: http://localhost:8020/flightsearch
     

security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false